### ISSUE TITLE
rviz.launch refers to 'dr_extrinsic_calibration' which doesn't exist

### ISSUE THREAD

**Issue by gavanderhoorn** [delftrobotics/camera_pose_calibration#1]
[here](https://github.com/delftrobotics/camera_pose_calibration/blob/723ed582ce2c9af4a86be75dc17cf928ad44d650/launch/rviz.launch#L2).

Copy/pasta?

**Comment by de-vri-es** [comment]
Thanks for reporting. Ronald was on vacation and so was I, but it is fixed now in c4244e57b5914f6960af521377034af9c97b73d0
