### ISSUE TITLE
No output + Unclear Things

### ISSUE THREAD

**Issue by eyildiz-ugoe** [delftrobotics/camera_pose_calibration#11]
I've my pattern fixed on the workstation, and my "world" (which is another fixed frame) frame's origin, let's say, is my pattern's origin, since I don't have a robot and I don't want to have a different frame. So my camera and the world frames are basically having the same origin.

Given this, I execute the following commands:

` rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 1.0 world pattern 1000`

`roslaunch camera camera.launch`

`roslaunch camera_pose_calibration nodelet.launch`

` rosservice call /calibrate_topic "tag_frame: 'pattern'
target_frame: 'map'
point_cloud_scale_x: 1.0
point_cloud_scale_y: 1.0
pattern: {pattern_width: 4, pattern_height: 11, pattern_distance: 4.0}" 
`

However the last command doesn't return anything. No errors, no results, nothing. I check `rostopic echo /detected_pattern` and there is nothing in there either. Here is my how stereo images look like:

![1](https://user-images.githubusercontent.com/35396058/59273735-2e672380-8c59-11e9-9433-95524fa2922f.png)
![2](https://user-images.githubusercontent.com/35396058/59273736-2e672380-8c59-11e9-98be-fef990f5126c.png)

I don't know what's wrong, but it doesn't seem to work.

Apart from that, there are a couple of issues with this package, which makes the whole process frustrating.

1. `The right-top corner blob is defined as the origin` must be marked on that image. Depending on how you look at this pattern, the statement is ambiguous at the best.

2. Chain of commands is missing. What to run first, what's the order? Static publisher and then the nodelet, or?

3. `The pose of the camera to the fixed frame will then be returned and optionally published.` the command returns nothing, and nothing is published. There is no single error message or whatsoever. One spends a lot of time without a result.

4. `The circle center-to-center distance of the printed pattern.` which unit is the distance in? Cm?

**Comment by RonaldEnsing** [comment]
I agree that the both the documentation and error handling should improve. However, this project is no longer actively maintained. I don't expect any updates. To find out why your service call hangs, I would suggest to check if your topics are remapped correctly. Use a debugger to find out where the code hangs. Start using the node (not the nodelet) and one of the service calls of your preference. The circle-to-circle distance should have the same units as your camera intrinsics.

**Comment by eyildiz-ugoe** [comment]
Since there was no single word of topic remapping, I obviously did not do anything in that regard. Anyway, thank you, I guess it's quite problematic to get this working and I'll skip it.
