### ISSUE TITLE
dr_base can not be found 

### ISSUE THREAD

**Issue by BENKRID-abdenour** [delftrobotics/camera_pose_calibration#2]
Hi,
i want to calibrate my kinect for more accuracy in order to build a 3D map , the problem with this package is the dependency 'dr_base' , i can not find it.

when i try to compile the package The catkin_make command give this error : 

Could not find the required component 'dr_base'. 

please help

**Comment by hgaiser** [comment]
Hey,

The package you are looking for can be found here:

https://github.com/delftrobotics/dr_base

Good luck setting things up and let us know if there are any issues, we would like to hear the feedback :).

**Comment by BENKRID-abdenour** [comment]
many thanks , it works
