### ISSUE TITLE
target_frame parameter is unused

### ISSUE THREAD

**Issue by AndyZe** [delftrobotics/camera_pose_calibration#6]
master branch:

When using calibrateFile, part of the service request is **target_frame**. This parameter appears to be unused. Here's the output when **srv.tag_frame** is set to calibration_circles_frame, and **srv.target_frame** is set to base_link. Notice that base_link doesn't appear.

Have you guys actually tested the package yet? The tf's I'm getting are not even close to aligned right, but that could very well be user error on my end.
![unused_target_frame](https://cloud.githubusercontent.com/assets/11284393/24712905/c7add2c6-19e9-11e7-84dd-f4a1ab69dbb3.png)

**Comment by AndyZe** [comment]
Also, regarding that picture, it looks like the inverse wasn't calculated correctly:
```
ROS_INFO_STREAM(cloud->header.frame_id << " to " << tag_frame << " :\n" << camera_to_tag.matrix() );

ROS_INFO_STREAM(tag_frame << " to " << cloud->header.frame_id << " :\n" << camera_to_tag.matrix().**inverse()** );

ROS_INFO_STREAM(cloud->header.frame_id << " to " << target_frame << " :\n" << camera_to_target.matrix() );
```

The inverse should be ~
-.47 .63 -1.12  4.05
.76 .65 .16 -6.57
.83 -.78 .18 -2.06
0 0 0 1

**Comment by de-vri-es** [comment]
Are you sure you're on the latest master branch? The `target_frame` parameter is passed on to the `calibrate` function: https://github.com/delftrobotics/camera_pose_calibration/blob/d12976f6b6a7597dbb116474db6dc1b88200b0a4/src/node.cpp#L296

Additionally, I can't find the print statements you are referring to. What I can find is these:
https://github.com/delftrobotics/camera_pose_calibration/blob/d12976f6b6a7597dbb116474db6dc1b88200b0a4/src/node.cpp#L258

/edit: The inverse of camera_to_tag isn't printed at all by those print statements.

**Comment by AndyZe** [comment]
Thank you for more suggestions. Yes, I'm definitely up-to-date with the latest.

Yes, the middle print statement was added by me for debugging.

Please ignore my previous statement about the inverse being incorrect. I wrote a test program and the inversion seems to be working correctly.

I'm still confused about why base_link (i.e. my target frame) doesn't appear in the output at all.

Sorry for all the questions. My original intention was to figure this stuff out and add some documentation to make it easier for others.

**Comment by AndyZe** [comment]
I'm going to make a pull request. It has a new branch with my test programs and data.

**Comment by RonaldEnsing** [comment]
How does your full tf tree look like? The tf's corresponding to the camera should be disconnected from the tf's corresponding to the robot before calibration, and connected after calibration if you choose to publish the resulting tf.

On the picture in your PR, it seems like you are calibrating two robots, is that correct? As far as I know, this has not been tested yet. It should work, but still I would recommend to start with calibrating one robot.

I suppose the camera is not mounted on the robot and you are looking for the calibration between base link and camera, is that correct? Did you measure the position and orientation of the asymmetric circles pattern correctly with respect to the ur_base_link?

You could also start with calibrating without any ROS services, but just by simply calling the appropriate findCalibration function in camera_pose_calibration.hpp and see if the resulting isometry seems reasonable.

**Comment by de-vri-es** [comment]
> I'm still confused about why base_link (i.e. my target frame) doesn't appear in the output at all.

Yes, it definitely should. I'll do some more digging when I can get round to it.

> Sorry for all the questions. My original intention was to figure this stuff out and add some documentation to make it easier for others.

That would be very awesome. I'm sorry to say we haven't really had the time to do that properly.

**Comment by AndyZe** [comment]
> How does your full tf tree look like? The tf's corresponding to the camera should be disconnected from the tf's corresponding to the robot before calibration, and connected after calibration if you choose to publish the resulting tf.

Thanks, that's helpful. The camera was connected in the URDF previously. Maybe that's why the target_frame didn't show up in the output. Fixing that so the camera is originally unconnected now.

> On the picture in your PR, it seems like you are calibrating two robots, is that correct?

We have 2 robots, but I was only calibrating 1. 

> Did you measure the position and orientation of the asymmetric circles pattern correctly with respect to the ur_base_link?

I think so, here's a picture of that. The camera is the red blob on the end-effector.
![cal_setup](https://cloud.githubusercontent.com/assets/11284393/25027748/a3825660-2074-11e7-9baa-b69ab29bdf71.jpg)

And a picture of the output, after converting the rotation to quaternion and using a static transform publisher:
`tf::Quaternion quat(srv.response.transform.rotation.x, srv.response.transform.rotation.y, srv.response.transform.rotation.z, srv.response.transform.rotation.z);

  quat.normalize();

  ROS_INFO_STREAM("Camera translation: " << std::endl << srv.response.transform.translation );
  ROS_INFO_STREAM("Camera rotation (quaternion): " << std::endl << quat.x() <<"  "<< quat.y() <<"  "<< quat.z() <<"  "<< quat.w() );`

![bad_cal](https://cloud.githubusercontent.com/assets/11284393/25027771/d46b8aa8-2074-11e7-9bd8-f8b75a14f310.png)

**Comment by AndyZe** [comment]
Since I don't trust my quaternion conversion code, here's the result when I ask camera_pose_calibration_node to publish the transform. I just set the parameters "publish_transform=true" and "publish_rate=100", as Ronald indicated. The tf still doesn't look right...
e572bd00b0e8c35261aefab3c682c9aaf0b94eb4
![tf_published_by_cal_node](https://cloud.githubusercontent.com/assets/11284393/25046467/3ba00546-20f7-11e7-9b56-6635cd04605d.jpg)

**Comment by AndyZe** [comment]
I messed around with the parameters and have finally gotten an image that is, at least, in the right plane. A 45 deg rotation and an offset will finish this off.  b36e0ae
![in_the_plane](https://cloud.githubusercontent.com/assets/11284393/25396349/e0b85352-29a9-11e7-996f-11367d174fce.png)

**Comment by AndyZe** [comment]
I think the previous error occurred because I expected the point cloud to publish in camera_ee_depth_frame, but it was actually published in camera_ee_depth_optical_frame. (as well as the parameter tuning issues)

**Comment by de-vri-es** [comment]
hmm, don't we use stamped transforms everywhere in the ROS interface? They should automatically contain the correct frame IDs. Is there something we can improve here?

**Comment by AndyZe** [comment]
Hey Martin, I was using this pointcloud from a pcd file, so I _think_ there would be no frame attached to that information.

**Comment by de-vri-es** [comment]
Ah, good point. PCD files indeed don't store the frame ID [1]. It does contain `viewpoint` metadata, but that isn't what we need.

[1] http://pointclouds.org/documentation/tutorials/pcd_file_format.php
