### ISSUE TITLE
Pattern msg type

### ISSUE THREAD

**Issue by dipendras** [delftrobotics/camera_pose_calibration#9]
I am calibrating a kinect with this package but I couldnot find enough description on how to define a Pattern msg type with distance and size of the asymmetric circles pattern. I am using the pattern from this link: https://nerian.com/support/resources/patterns/ with A4 size patterns.

Can you help me fix this? Thanks in advance.

**Comment by RonaldEnsing** [comment]
An explanation of `pattern_width`, `pattern_height` and `pattern_distance` can be found here: [https://docs.opencv.org/3.0-beta/doc/tutorials/calib3d/camera_calibration/camera_calibration.html](https://docs.opencv.org/3.0-beta/doc/tutorials/calib3d/camera_calibration/camera_calibration.html)

So in your case the `pattern_width` is 4 and the `pattern_height` is 11.

The `pattern_distance` is the circle center-to-center distance. This is something you need to measure if you print it on paper.

The `neighbor_distance` and `valid_pattern_ratio_threshold` are optional, so you could leave them to their default values of 0. If they are set to 0, they will be ignored. `neighbor_distance` is a radius in pixels in which `(x, y, z)` values are averaged to reduce the impact of noise in the `(x, y, z)` values. `valid_pattern_ratio_threshold` is a threshold value between 0 and 1 on an acceptable ratio of `NaN` values.

**Comment by dipendras** [comment]
But it still shows "segmentation fault" when I run: rosrun camera_pose_calibration camera_pose_calibration_node.

When I try running the launch file: roslaunch camera_pose_calibration nodelet.launch, it shows "Bond broken, exiting". Can you tell me how to fix this?

**Comment by RonaldEnsing** [comment]
I would suggest that you compile the project in debug mode and run it with a debugger. Then find out where and why the segmentation fault occurs.

**Comment by dipendras** [comment]
Thanks for your help.
